# node.js base image
FROM node:14-alpine

# server info
RUN node -v
RUN npm -v

# install nodemon for development purpose
RUN npm install -g pm2

# working directory
WORKDIR /app
COPY ./dist /app
COPY ./.npmrc /app/.npmrc
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install --production

# start server
CMD ["pm2-docker", "start", "server.js"]